## BACK config/cable.yml
development:
  adapter: async
test:
  adapter: async
production:
  adapter: redis
  url: redis://h:p9e2e1a7daa59fcc5b799b96afa52bdb0e2ef72abace530fb84fa732ed727d116@ec2-34-225-156-155.compute-1.amazonaws.com:19229
  channel_prefix: qsmart-api_production